# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile:  '$(Build.SourcesDirectory)/Examples/output/ArrangeMeasureOverride'
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/ArrangeMeasureOverride_$(Build.BuildId).zip'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile:  '$(Build.SourcesDirectory)/Examples/output/TaskComplitionSource'
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/TaskComplitionSource_$(Build.BuildId).zip'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile:  '$(Build.SourcesDirectory)/Examples/output/EngineDatabaseSetup/EngineDatabaseSetup.msi'
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/EngineDatabaseSetup_$(Build.BuildId).zip'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile:  '$(Build.SourcesDirectory)/Examples/output/EngineDatabaseBootstrapper/EngineDatabaseBootstrapper.exe'
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/EngineDatabaseBotstrapper_$(Build.BuildId).zip'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'PVikMboxProject'
